version: "3.9"

services:
  web:
    container_name: telegram-anime-bot
    restart: always
    image: 389798/telegram-image
    build: ./
    env_file: .env
    depends_on:
      - redis
    volumes:
      - C:\Users\Игорь\Documents\anime_bot:/app/

  redis:
    image: redis
    container_name: svc-redis
    ports:
      - 6379:6379
    command: ["redis-server", "--bind", "redis", "--port", "6379"]
    volumes:
      - C:\Users\Игорь\Documents\anime_bot\redis:/usr/local/etc/redis

networks:
  default:

volumes:
  redis:
